# -*- coding: utf-8 -*-
"""GD.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EtT8KQaZSjO6RmeGqRHG2_yKdn6HgvUZ
"""

import numpy as np
import matplotlib.pyplot as plt

f = lambda theta: theta[0]**2 + theta[1]**2+3*theta[0]+theta[0]*theta[1]

theta_t = np.array([0.0,0.0]) 
alpha = 0.1
l = []
for i in range(50):
  g = np.array( [2*theta_t[0]+3+ theta_t[1] , 2*theta_t[1]+theta_t[0]    ]    )
  theta_t -= alpha * g 
  l.append(f(theta_t))

print(theta_t)
plt.plot(l, 'r-x')
plt.show()